[package]
name = "sunshade"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
tokio = { version = "1", features = ["full"] }
crossterm = "0.26"
dotenvy = "0.15.7"
